import type { Metadata } from "next";

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Poppins } from 'next/font/google';
import ProviderApp from "@/provider";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ProviderApp>
          {children}
        </ProviderApp>
      </body>
    </html>
  );
}
